# NumPy Basics

In [2]:
# Importing
import numpy as np

## Creation of np.array

In [3]:
# Creation of np.array from list
list_a = [1, 2, 3]
a = np.array(list_a)
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [4]:
# 2D array
list_b = [[1, 0, 0],
          [0, 1, 0],
          [0, 0, 1]]
b = np.array(list_b)
print(b)
print(type(b))
print(b.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
(3, 3)


In [5]:
# To create arrays of 0s and 1s
zero_array = np.zeros((2,3))
one_array = np.ones((3,4))
print(zero_array)
print(one_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Generating random numbers
c = np.random.randint(low=1, high=10, size=(3,3))
d = np.random.rand(8, 3)
e = np.random.random_sample((3, 4))
print(c)
print(d)
print(e)

[[8 3 7]
 [1 6 7]
 [4 2 2]]
[[0.12083134 0.96991828 0.48114107]
 [0.70369664 0.08940654 0.4341117 ]
 [0.51285484 0.25083362 0.67987117]
 [0.61780065 0.85928131 0.9215086 ]
 [0.54239581 0.01426082 0.48259088]
 [0.25361604 0.78344609 0.87399912]
 [0.24178639 0.45327181 0.54183762]
 [0.91572244 0.98074987 0.6972463 ]]
[[0.29375764 0.59859109 0.69223971 0.19268378]
 [0.3126923  0.33072378 0.51106129 0.72010044]
 [0.61643879 0.06141194 0.46720664 0.59972718]]


## Reshaping arrays

In [7]:
# Reshaping arrays into required shape
d_1 = np.reshape(d, newshape=(6, 4))
# In order to reshape from 8x3 to 6x4, size can also be mentioned as (6, -1)
# The remaining factor (in place of -1) is automatically computed
d_2 = d.reshape((6, -1))
print(d_1)
print(d_2)
print(d_1 == d_2)

[[0.12083134 0.96991828 0.48114107 0.70369664]
 [0.08940654 0.4341117  0.51285484 0.25083362]
 [0.67987117 0.61780065 0.85928131 0.9215086 ]
 [0.54239581 0.01426082 0.48259088 0.25361604]
 [0.78344609 0.87399912 0.24178639 0.45327181]
 [0.54183762 0.91572244 0.98074987 0.6972463 ]]
[[0.12083134 0.96991828 0.48114107 0.70369664]
 [0.08940654 0.4341117  0.51285484 0.25083362]
 [0.67987117 0.61780065 0.85928131 0.9215086 ]
 [0.54239581 0.01426082 0.48259088 0.25361604]
 [0.78344609 0.87399912 0.24178639 0.45327181]
 [0.54183762 0.91572244 0.98074987 0.6972463 ]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# Task: Try to reshape the array into a 3D array of shape 2x3x4

## Deletion of elements

In [8]:
# Deletion of rows/columns
d_col_delete = np.delete(d, 1, axis=1)
d_row_delete = np.delete(d, 2, axis=0)
print(d_col_delete.shape)
print(d_row_delete.shape)

(8, 2)
(7, 3)


In [ ]:
# Learn the concepts of axis properly
# Check StackOverflow or NumPy documentation for more details

In [ ]:
# Task: Delete a particular element of array `c`

## Merging Rows or Columns

In [9]:
# Merging Rows/Columns
merge_rows = np.vstack((c, d))
merge_cols = np.hstack((c, e))

In [12]:
print(merge_rows)

[[8.         3.         7.        ]
 [1.         6.         7.        ]
 [4.         2.         2.        ]
 [0.12083134 0.96991828 0.48114107]
 [0.70369664 0.08940654 0.4341117 ]
 [0.51285484 0.25083362 0.67987117]
 [0.61780065 0.85928131 0.9215086 ]
 [0.54239581 0.01426082 0.48259088]
 [0.25361604 0.78344609 0.87399912]
 [0.24178639 0.45327181 0.54183762]
 [0.91572244 0.98074987 0.6972463 ]]


In [13]:
print(merge_cols)

[[8.         3.         7.         0.29375764 0.59859109 0.69223971
  0.19268378]
 [1.         6.         7.         0.3126923  0.33072378 0.51106129
  0.72010044]
 [4.         2.         2.         0.61643879 0.06141194 0.46720664
  0.59972718]]


In [ ]:
# Task: Try using np.concatenate to perform the above operations

# Aggregate Functions

In [ ]:
# Task: Find the row-wise minimum of the array `c`
# Task: find the column-wise mean of array `d`
# Task: Find the row-wise mean of array `e`
# Task: Find the maximum of all values in the array `c`